version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    env_file: ./backend/docker/.env
    depends_on:
      - postgres
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    ports:
      - 8081:8080
    restart: unless-stopped
    environment:
      - API_HOST=backend
      - API_PORT=3000
      - PORT=8080
  postgres:
    image: postgres:11.5-alpine
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: ./backend/.env
    restart: unless-stopped