version: '3'

services:
  postgres:
    image: postgres:11.5-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
    restart: unless-stopped